Fix missing settings
Error during bootstrap of cat:
File "/app/cat/plugins/cc_vscode_debugpy/cc-vscode-debugpy.py", line 27, in before_cat_bootstrap
     settings = cat.mad_hatter.plugins[PLUGIN_NAME].load_settings()
 KeyError: 'cc-vscode-debugpy'

After initial installation settings file is no there.

Handle the KeyError exception